name: 'pre-release'

on:
  push:
    branches:
      - 'main'

jobs:
  pre-release:
    name: 'Pre Release'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'v${{ GITHUB_RUN_NUMBER }}'
          prerelease: true
          title: 'v${{ GITHUB_RUN_NUMBER }}'
          files: |
            dist/sparkles.js
