name: 'pre-release'

on:
  push:
    branches:
      - 'main'

jobs:
  pre-release:
    name: 'Pre Release'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - uses: einaregilsson/build-number@v3
        id: buildnumber
        with:
          token: ${{secrets.github_token}}
          prefix: 'v'

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
        env:
          VERSION: 'v${{ steps.buildnumber.outputs.build_number }}'

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'v${{ steps.buildnumber.outputs.build_number }}'
          prerelease: false
          title: 'Release v${{ steps.buildnumber.outputs.build_number }}'
          files: |
            dist/sparkles.js
